import type { BrancheFaq } from './types'

/** Karten-Reihenfolge = sichtbares Grid + ItemList-Schema */
export const BRANCHEN_HUB_CARDS = [
  {
    slug: 'aerzte',
    title: 'Ärzte & Arztpraxen',
    description: 'Mehr Patientenanfragen über Google: Local SEO für Praxen und Kliniken.',
    go: 'SEO für Ärzte',
    schemaName: 'SEO für Ärzte',
    image: '/images/blog/branche-aerzte.webp',
    alt: 'Arzt im weißen Kittel geht mit Tablet durch den Flur einer modernen Praxis',
    featured: true,
    priority: true,
  },
  {
    slug: 'handwerker',
    title: 'Handwerker',
    description: 'Mehr Aufträge über Google: Elektriker, Sanitär, Schreiner, Maler und Co.',
    go: 'SEO für Handwerker',
    schemaName: 'SEO für Handwerker',
    image: '/images/blog/branche-handwerker.webp',
    alt: 'Hände eines Schreiners hobeln eine Eichenbohle in der Werkstatt',
    featured: true,
    priority: false,
  },
  {
    slug: 'zahnaerzte',
    title: 'Zahnärzte',
    description: 'Mehr Patienten für deine Zahnarztpraxis: Local SEO und Google Maps.',
    go: 'SEO für Zahnärzte',
    schemaName: 'SEO für Zahnärzte',
    image: '/images/blog/branche-zahnaerzte.webp',
    alt: 'Zahnarzt behandelt eine Patientin in moderner Zahnarztpraxis, Aufnahme über die Schulter',
    featured: false,
    priority: false,
  },
  {
    slug: 'anwaelte',
    title: 'Anwälte & Kanzleien',
    description: 'Mandantenanfragen mit relevanter Suchintention für deine Kanzlei.',
    go: 'SEO für Anwälte',
    schemaName: 'SEO für Anwälte',
    image: '/images/blog/branche-anwaelte.webp',
    alt: 'Anwalt steht am Schreibtisch einer Kanzlei und liest eine Akte, Bücherwand im Hintergrund',
    featured: false,
    priority: false,
  },
  {
    slug: 'steuerberater',
    title: 'Steuerberater',
    description: 'Online-Sichtbarkeit für Steuerkanzleien: neue Mandate über Google.',
    go: 'SEO für Steuerberater',
    schemaName: 'SEO für Steuerberater',
    image: '/images/blog/branche-steuerberater.webp',
    alt: 'Steuerberatung am Konferenztisch, Hand zeigt auf eine Auswertung neben dem Laptop',
    featured: false,
    priority: false,
  },
  {
    slug: 'immobilienmakler',
    title: 'Immobilienmakler',
    description: 'Sichtbarkeit für Verkauf, Vermietung und Makler in München.',
    go: 'SEO für Immobilienmakler',
    schemaName: 'SEO für Immobilienmakler',
    image: '/images/blog/branche-immobilienmakler.webp',
    alt: 'Schlüsselübergabe in einer hellen leeren Wohnung mit Parkettboden',
    featured: false,
    priority: false,
  },
  {
    slug: 'restaurants',
    title: 'Restaurants & Gastronomie',
    description: 'Mehr Gäste über Google Maps, Speisekarte und Reservierungen.',
    go: 'SEO für Restaurants',
    schemaName: 'SEO für Restaurants',
    image: '/images/blog/branche-restaurants.webp',
    alt: 'Kellner trägt Teller durch ein elegant gedecktes Restaurant',
    featured: false,
    priority: false,
  },
  {
    slug: 'physiotherapeuten',
    title: 'Physiotherapeuten',
    description: 'Mehr Patienten über Google: Selbstzahler und Local SEO, das HWG im Blick.',
    go: 'SEO für Physiotherapeuten',
    schemaName: 'SEO für Physiotherapeuten',
    image: '/images/blog/branche-physiotherapeuten.webp',
    alt: 'Physiotherapeutin behandelt Schulter und Rücken eines Patienten auf der Liege',
    featured: false,
    priority: false,
  },
  {
    slug: 'hotels',
    title: 'Hotels',
    description: 'Mehr Direktbuchungen, weniger Portal-Provision: Local SEO für dein Haus.',
    go: 'SEO für Hotels',
    schemaName: 'SEO für Hotels',
    image: '/images/blog/branche-hotels.webp',
    alt: 'Rezeptionistin am Marmorempfang einer Hotellobby mit Messingleuchten',
    featured: false,
    priority: false,
  },
  {
    slug: 'kfz-werkstatt',
    title: 'KFZ-Werkstätten',
    description: 'Mehr Anfragen über Maps, Leistungsseiten und Bewertungen.',
    go: 'SEO für KFZ-Werkstätten',
    schemaName: 'SEO für KFZ-Werkstätten',
    image: '/images/blog/branche-kfz-werkstatt.webp',
    alt: 'Mechaniker arbeitet unter der geöffneten Motorhaube in einer KFZ-Werkstatt',
    featured: false,
    priority: false,
  },
] as const

/** Hub-FAQs — sichtbar + FAQPage Schema zeichenidentisch */
export const BRANCHEN_HUB_V2_FAQS: BrancheFaq[] = [
  {
    q: 'Was bringt branchenspezifisches SEO im Vergleich zu allgemeinem SEO?',
    a: 'Branchenspezifisches SEO zielt auf die exakten Suchbegriffe, die potenzielle Kunden in deiner Branche verwenden. Ein Zahnarzt wird mit anderen Keywords gesucht als ein Handwerker. Durch die gezielte Optimierung auf branchenrelevante Begriffe und lokale Suchintentionen erreichst du qualifiziertere Besucher, die tatsächlich nach deiner Dienstleistung suchen.',
  },
  {
    q: 'Wie lange dauert es, bis SEO-Maßnahmen für meine Branche wirken?',
    a: 'Erfahrungsgemäß sind erste messbare Ranking-Verbesserungen nach 3 bis 6 Monaten sichtbar, bei weniger umkämpften lokalen Keywords oft schneller. Die genaue Dauer hängt vom Wettbewerb in deiner Branche und vom Zustand deiner Website ab.',
  },
  {
    q: 'Was kostet SEO für meine Branche in München?',
    a: 'Die Kosten richten sich nach Branche und Wettbewerbssituation. Für lokale Dienstleister wie Ärzte, Anwälte oder Handwerker starten unsere Pakete bei 990 EUR pro Monat (Starter). Branchen mit stärkerem Online-Wettbewerb wie Immobilien oder Hotels brauchen in der Regel ein höheres Budget. Im kostenlosen Erstgespräch analysieren wir deine Situation und geben dir eine konkrete Einschätzung.',
  },
  {
    q: 'Funktioniert SEO auch für Branchen mit wenig Online-Konkurrenz?',
    a: 'Gerade dann bietet SEO großes Potenzial. Wenn deine Mitbewerber noch nicht in SEO investieren, kannst du dir gute Positionen sichern, bevor der Markt nachzieht. Viele Handwerksbetriebe und lokale Dienstleister in München profitieren genau davon: weniger Wettbewerb bedeutet oft schnellere sichtbare Fortschritte.',
  },
]
